@baseUrl = http://127.0.0.1:8000/api
@token = 68|mbP05z1hnE4ZtuV4HoJAYe4B4jZRZfnirVsA0HXG9ea7c389


### Login with username
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "login": "superadmin",
    "password": "123456"
}

### Get All Departments
GET {{baseUrl}}/master/departments/search
Authorization: Bearer {{token}}
Accept: application/json

### Get All Departments (No Pagination)
GET {{baseUrl}}/master/departments/all
Authorization: Bearer {{token}}
Accept: application/json

### Get Department by ID
GET {{baseUrl}}/master/departments/1
Authorization: Bearer {{token}}
Accept: application/json

### Create Department
POST {{baseUrl}}/master/departments
Content-Type: application/json
Authorization: Bearer {{token}}
Accept: application/json

{
    "code": "IT",
    "name": "Information Technology"
}

### Update Department
PUT {{baseUrl}}/master/departments/14
Content-Type: application/json
Authorization: Bearer {{token}}
Accept: application/json

{
    "location_code": "000H-ACC"
}

### Get curlocs distinct
GET {{baseUrl}}/master/departments/cur-locs
Authorization: Bearer {{token}}



