@baseUrl = http://127.0.0.1:8000/api
@token = 50|IYgXc2ILq7FlZtwwXWemSDWB4Nh0GhT8uEm1SdDl1125ded9

### Login with username
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "login": "superadmin",
    "password": "123456"
}

### Get all suppliers
GET {{baseUrl}}/master/suppliers/all?type=vendor
Authorization: Bearer {{token}}
Accept: application/json

### search suppliers
GET {{baseUrl}}/master/suppliers/search?type=vendor
Authorization: Bearer {{token}}
Accept: application/json

### update supplier
PUT {{baseUrl}}/master/suppliers/3
Content-Type: application/json
Authorization: Bearer {{token}}
Accept: application/json

{
    "sap_code": "CKPUCIDR01",
    "name": "Solusi Bangun Indonesia, PT"
}

### check target
GET {{baseUrl}}/master/suppliers/cek-target
Authorization: Bearer {{token}}
Accept: application/json

### import supplier
GET {{baseUrl}}/master/suppliers/import
Authorization: Bearer {{token}}
Accept: application/json

### Check Supplier payment project
GET {{baseUrl}}/master/suppliers/get-payment-project?supplier_id=1
Authorization: Bearer {{token}}

### Check ITO Import (Pre-import validation)
POST {{baseUrl}}/master/ito/import-check
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

### Import ITO Data
POST {{baseUrl}}/master/ito/import
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

### Get all projects
GET {{baseUrl}}/master/projects/all
Authorization: Bearer {{token}}
Accept: application/json

### Search projects
GET {{baseUrl}}/master/projects/search
Authorization: Bearer {{token}}
Accept: application/json

### Create new project
POST {{baseUrl}}/master/projects
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "code": "PRJ001",
    "owner": "John Doe",
    "location": "Jakarta"
}

### Update project
PUT {{baseUrl}}/master/projects/1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "code": "PRJ001",
    "owner": "Jane Doe",
    "location": "Bandung"
}

### Delete project
DELETE {{baseUrl}}/master/projects/1
Authorization: Bearer {{token}}
Accept: application/json

### Get all invoice types
GET {{baseUrl}}/master/invoice-types/all
Authorization: Bearer {{token}}
Accept: application/json

### Search invoice types
GET {{baseUrl}}/master/invoice-types/search
Authorization: Bearer {{token}}
Accept: application/json

### Create new invoice type
POST {{baseUrl}}/master/invoice-types
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "type_name": "Regular Invoice"
}

### Update invoice type
PUT {{baseUrl}}/master/invoice-types/1
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "type_name": "Updated Invoice Type"
}

### Delete invoice type
DELETE {{baseUrl}}/master/invoice-types/1
Authorization: Bearer {{token}}
Accept: application/json



